TRUNCATE user_challenge_entries RESTART IDENTITY CASCADE; 

INSERT INTO user_challenge_entries(challenge_id, users_id, pass, score, notes)
VALUES
(1, 1, FALSE, 23, 'not so good' ),
(2, 1, FALSE , 12, 'even worse' ),
(1, 2, TRUE, 100, 'super awesome' ),
(2, 2, TRUE , 200, 'killed it' );

    -- id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    -- challenge_id INTEGER REFERENCES challenges(id) NOT NULL,
    -- user_id INTEGER REFERENCES users(id) NOT NULL, 
    -- pass BOOLEAN NOT NULL, 
    -- score INTEGER, 
    -- notes TEXT 