-- CHANGE age should be birth date, then calculate age based on birth date

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  users_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL, 
  users_pic_url TEXT NOT NULL,  
  birth_date DATE NOT NULL
);
