-- CHANGE age should be birth date, then calculate age based on birth date

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL, 
  pic_url TEXT NOT NULL,  
  dragon_bucks MONEY NOT NULL, 
  age INTEGER NOT NULL
);
