-- DO $$
-- BEGIN
--     IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'community') THEN
--         CREATE TYPE community AS ENUM ('Grodojo', 'Dragon Root', 'Public');
--     END IF;
-- END
-- $$; 
DROP TABLE IF EXISTS communities; 

CREATE TABLE communities(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    community_type TEXT NOT NULL
)