DROP TABLE IF EXISTS challenges_communities; 

CREATE TABLE challenges_communities(
    challenges_communities_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    challenges_id INTEGER REFERENCES challenges(challenges_id) ON DELETE CASCADE NOT NULL, 
    communities_id INTEGER REFERENCES communities(communities_id) ON DELETE CASCADE NOT NULL 
);