DROP TABLE IF EXISTS user_challenge_entries; 

CREATE TABLE user_challenge_entries(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    challenge_id INTEGER REFERENCES challenges(id) ON DELETE CASCADE NOT NULL,
    users_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL, 
    pass BOOLEAN NOT NULL, 
    score INTEGER, 
    notes TEXT 
)