DROP TABLE IF EXISTS sub_communities; 

CREATE TABLE sub_communities(
    sub_communities_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    communities_id INTEGER REFERENCES communities(communities_id) ON DELETE CASCADE NOT NULL, 
    sub_communities_name TEXT NOT NULL
)