DROP TABLE IF EXISTS users_sub_communities;

CREATE TABLE users_sub_communities(
    users_sub_communities_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    users_id INTEGER REFERENCES users(users_id) ON DELETE CASCADE NOT NULL, 
    sub_communities_id INTEGER REFERENCES sub_communities(sub_communities_id) ON DELETE CASCADE NOT NULL
);