CREATE TABLE all_badges(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pillar_id INTEGER REFERENCES pillars(id) ON DELETE CASCADE NOT NULL,
    badge_name TEXT NOT NULL, 
    pic_url TEXT NOT NULL, 
    star_rating INTEGER NOT NULL, 
    badge_description TEXT NOT NULL, 
    passing_num INTEGER, 
    number_description TEXT
);