DROP TABLE IF EXISTS challenges; 

CREATE TABLE challenges(
    challenges_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    challenges_name TEXT NOT NULL,
    challenges_pic_url TEXT NOT NULL, 
    units TEXT NOT NULL
);