DROP TABLE IF EXISTS user_challenges; 

CREATE TABLE user_challenges(
    user_challenges_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    challenges_id INTEGER REFERENCES challenges(challenges_id) ON DELETE CASCADE NOT NULL,
    users_id INTEGER REFERENCES users(users_id) ON DELETE CASCADE NOT NULL, 
    pass BOOLEAN NOT NULL, 
    score INTEGER, 
    notes TEXT 
)