DROP TABLE IF EXISTS challenge_types;

DROP TYPE IF EXISTS best_record; 
CREATE TYPE best_record AS ENUM('lowest', 'highest');

CREATE TABLE challenge_types(
    challenge_types_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    challenge_types_name TEXT NOT NULL,
    challenge_types_description TEXT NOT NULL,
    challenge_types_best_record best_record,
    units TEXT NOT NULL
);
