DROP TABLE IF EXISTS challenge_types; 

CREATE TABLE challenge_types(
    challenge_types_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    challenge_types_name TEXT NOT NULL,
    challenge_types_pic_url TEXT NOT NULL, 
    units TEXT NOT NULL
);