DROP TABLE IF EXISTS users_challenge_instances;

CREATE TABLE users_challenge_instances(
    users_challenge_instances_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    users_id INTEGER REFERENCES users(users_id) ON DELETE CASCADE NOT NULL,
    challenge_types_id INTEGER REFERENCES challenge_types(challenge_types_id) ON DELETE CASCADE NOT NULL,
    entry_date DATE NOT NULL,
    record INTEGER NOT NULL,
    notes TEXT
);
