DROP TABLE IF EXISTS challenge_instances; 

CREATE TABLE challenge_instances(
    challenge_instances_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    challenge_types_id INTEGER REFERENCES challenge_types(challenge_types_id) ON DELETE CASCADE NOT NULL, 
    challenge_instances_name TEXT NOT NULL, 
    challenge_instances_description TEXT NOT NULL,
    open_date DATE NOT NULL DEFAULT CURRENT_DATE, 
    close_date DATE NOT NULL, 
    stars_one_minimum INTEGER,
    stars_two_minimum INTEGER,
    stars_three_minimum INTEGER, 
    stars_one_bucks NUMERIC(7, 2),
    stars_two_bucks NUMERIC(7, 2),
    stars_three_bucks NUMERIC(7, 2)
)