DROP TABLE IF EXISTS users_communities_challenges; 

CREATE TABLE users_communities_challenges(
    users_communities_challenges_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    users_id INTEGER REFERENCES users(users_id) ON DELETE CASCADE NOT NULL,  
    communities_challenges_id INTEGER REFERENCES communities_challenges(communities_challenges_id) ON DELETE CASCADE NOT NULL,
    entry_date DATE NOT NULL, 
    record INTEGER,
    notes TEXT 
);