DROP TABLE IF EXISTS users_dragon_bucks; 
DROP TYPE IF EXISTS transaction_type; 

CREATE TYPE transaction_type as ENUM('Purchase', 'Penalty', 'Challenge Award', 'Other Award', 'Other');

CREATE TABLE users_dragon_bucks(
    users_dragon_bucks_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    dragon_bucks NUMERIC(8, 2),
    users_id INTEGER REFERENCES users(users_id) ON DELETE CASCADE NOT NULL,
    transaction_date DATE NOT NULL, 
    transaction_type transaction_type NOT NULL, 
    notes TEXT NOT NULL
);
