TRUNCATE TABLE user_challenges RESTART IDENTITY CASCADE; 

INSERT INTO user_challenges(challenges_id, users_id, pass, score, notes)
VALUES
(1, 1, FALSE, 11, 'notes 1' ),
(2, 1, FALSE , 21, 'notes 2' ),
(3, 1, TRUE, 31, 'notes 3' ),
(1, 2, TRUE , 12, 'notes 4' ),
(2, 2, FALSE, 22, 'notes 5' ),
(3, 2, FALSE , 32, 'notes 6' ),
(1, 3, TRUE, 13, 'notes 7' ),
(2, 3, TRUE , 23, 'notes 8' ),
(3, 3, TRUE , 33, 'notes 9' );

    -- user_challenges_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    -- challenges_id INTEGER REFERENCES challenges(challenges_id) ON DELETE CASCADE NOT NULL,
    -- users_id INTEGER REFERENCES users(users_id) ON DELETE CASCADE NOT NULL, 
    -- pass BOOLEAN NOT NULL, 
    -- score INTEGER, 
    -- notes TEXT 

