TRUNCATE TABLE communities_challenges RESTART IDENTITY CASCADE; 
 
 --('Jump Rope Challenge', 
-- ('Fitness Boxing',  
-- ('Archery Accuracy',  
-- ('1/2 Mile Run',

INSERT INTO communities_challenges(communities_id, challenges_id, communities_challenges_name, 
communities_challenges_description, open_date, close_date, stars_one_minimum, stars_two_minimum, stars_three_minimum, 
stars_one_bucks, stars_two_bucks, stars_three_bucks)
VALUES
(1, 1, 'Jumping That Rope', 'How many times can you jump rope?', '2019-07-01', '2019-07-31', 45, 60, 90, 1, 2, 3),
(3, 2, 'Fitness Boxing Fun', 'How long can you go with 100% accuracy?', '2019-07-01', '2019-07-31', 60, 90, 120, 1, 2, 3), 
(4, 3, 'Ace Archery', 'How many targets can you hit in 1 minute?', '2019-07-01', '2019-07-31', 5, 10, 15, 1, 2, 3),
(5, 4, 'Fun 1/2 Mile Run', 'How fast can you run a 1/2 mile?', '2019-07-01', '2019-07-31', 180, 150, 120, 1, 2, 3);
    -- communities_challenges_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- communities_id INTEGER REFERENCES communities(communities_id) ON DELETE CASCADE NOT NULL, 
    -- challenges_id INTEGER REFERENCES challenges(challenges_id) ON DELETE CASCADE NOT NULL, 
    -- open_date DATE NOT NULL DEFAULT CURRENT_DATE, 
    -- close_date DATE NOT NULL, 
    -- stars_one INTEGER,
    -- stars_two INTEGER,
    -- stars_three INTEGER, 
    -- stars_one_bucks NUMERIC(7, 2),
    -- stars_two_bucks NUMERIC(7, 2),
    -- stars_three_bucks NUMERIC(7, 2)

-- communities
-- 1, 'Green Dragons', 
-- 2, 'Grodojo', 
-- 3, 'Dragon Root',
-- 4, 'Urban Arrows', 
-- 5, 'Public';

-- challenges:  
-- 1, 'Cool Jump Rope Challenge', 
-- 2, 'Green Dragon Smoothie Challenge',
-- 3, 'Fitness Boxing Round at Dragon Root',  
-- 4, 'Archery Accuracy',  
-- 5, '1/2 Mile Run', 




