TRUNCATE TABLE users_dragon_bucks RESTART IDENTITY CASCADE; 

INSERT INTO users_dragon_bucks(dragon_bucks, users_id, transaction_date, transaction_type, notes)
VALUES
(-2.25, 1, '09-03-19', 'Purchase', 'chocolate bar'),
(-4.50, 1, '09-01-19', 'Purchase', 'video games'),
(-6.00, 1, '09-04-19', 'Purchase', 'push pop'),
(5.50, 1, '09-10-19', 'Challenge Award', '3 star challenge'),
(-1.75, 2, '09-02-19', 'Purchase', 'candy'),
(-3.25, 2, '09-12-19', 'Penalty', 'mean to other kids'),
(2.00, 2, '09-15-19', 'Challenge Award', '2 star challenge'),
(-5.75, 2, '09-01-19', 'Purchase', 'lots of candy'),
(-10.25, 3, '09-08-19', 'Penalty', 'poor behavior'),
(-20.00, 3, '09-20-19', 'Purchase', 'VIP treatment'),
(5.50, 3, '09-09-19', 'Challenge Award', 'awesome challenge work'),
(-30.75, 3, '09-04-19', 'Other', 'dandelion wine'); 

    -- users_dragon_bucks_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    -- dragon_bucks NUMERIC(8, 2),
    -- users_id INTEGER REFERENCES users(users_id) ON DELETE CASCADE NOT NULL,
    -- transaction_date DATE NOT NULL, 
    -- transaction_type transaction_type NOT NULL, 
    -- notes TEXT NOT NULL

    --CREATE TYPE transaction_type as ENUM('Purchase', 'Penalty', 'Challenge Award', 'Other Award', 'Other');